#!/usr/bin/env php
<?php
// application.php
require __DIR__.'/vendor/autoload.php';

require_once __DIR__ . '/CalculateCommand.php';

use Symfony\Component\Console\Application;


$application = new Application();

// ... register commands
$application->add(new CalculateCommand());
$application->run();